'use strict';

const DB_NAME='digital-score-v4';
const DB_VERSION=1;
const STORE='data';
const SNAP=.25;
const PX_PER_BEAT=88;
const PRE_ROLL=4;
const PITCH_COLORS={ド:'#ef5350',レ:'#ff9800',ミ:'#fdd835',ファ:'#66bb6a',ソ:'#42a5f5',ラ:'#5c6bc0',シ:'#ab47bc'};
const BUILTIN=[
 {id:'taiko',name:'たいこ',icon:'🥁'},{id:'bell',name:'すず',icon:'🔔'},{id:'tambourine',name:'タンバリン',icon:'🪘'},
 {id:'cymbal',name:'シンバル',icon:'◉'},{id:'triangle',name:'トライアングル',icon:'△'},{id:'castanet',name:'カスタネット',icon:'◒'},
 {id:'xylophone',name:'もっきん',icon:'🎼'},{id:'glockenspiel',name:'てっきん',icon:'🎼'},{id:'tonechime',name:'トーンチャイム',icon:'🔔'},
 {id:'piano',name:'ピアノ',icon:'🎹'},{id:'recorder',name:'リコーダー',icon:'🪈'},{id:'body',name:'ボディパーカッション',icon:'👏'}
];
const state={screen:'song',songs:[],instruments:[],sounds:[],patterns:[],projects:[],songId:null,instrumentIds:[],editIndex:0,seq:{},undo:[],playing:false,raf:0,soloId:null};
const $=id=>document.getElementById(id);
const uid=(p='id')=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const snap=v=>Math.max(0,Math.round(v/SNAP)*SNAP);
const selectedSong=()=>state.songs.find(x=>x.id===state.songId);
const allInst=()=>[...BUILTIN,...state.instruments];
const instById=id=>allInst().find(x=>x.id===id);
const soundById=id=>state.sounds.find(x=>x.id===id);

function db(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function getAll(){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function put(v){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(v);t.oncomplete=res;t.onerror=()=>rej(t.error);});}
async function del(id){const d=await db();return new Promise((res,rej)=>{const t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error);});}
function toast(t){const e=$('toast');e.textContent=t;e.hidden=false;clearTimeout(e._t);e._t=setTimeout(()=>e.hidden=true,2200);}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(`screen-${name}`).classList.add('active');state.screen=name;window.scrollTo(0,0);}

async function load(){const a=await getAll().catch(()=>[]);state.songs=a.filter(x=>x.kind==='song');state.instruments=a.filter(x=>x.kind==='instrument');state.sounds=a.filter(x=>x.kind==='sound');state.patterns=a.filter(x=>x.kind==='pattern');state.projects=a.filter(x=>x.kind==='project');renderSongs();renderInstruments();}
function latestProject(songId){return state.projects.filter(x=>x.songId===songId).sort((a,b)=>b.updatedAt-a.updatedAt)[0];}
async function saveProject(){if(!state.songId||!state.instrumentIds.length)return;let p=latestProject(state.songId);if(!p){p={id:uid('project'),kind:'project',songId:state.songId};state.projects.push(p);}p.instrumentIds=[...state.instrumentIds];p.seq=structuredClone(state.seq);p.updatedAt=Date.now();await put(p);}

function renderSongs(){const root=$('songGrid');root.innerHTML='';if(!state.songs.length)root.innerHTML='<div class="empty">まだ曲がありません。右上の「⚙ せんせい」から音声を追加します。</div>';for(const s of state.songs){const b=document.createElement('button');b.className='song-card'+(s.id===state.songId?' selected':'');b.innerHTML=`<strong>♫ ${esc(s.name)}</strong><span>${Number(s.bpm||120).toFixed(1)} BPM</span>`;b.onclick=async()=>{state.songId=s.id;const p=latestProject(s.id);if(p){state.instrumentIds=[...(p.instrumentIds||[])];state.seq=structuredClone(p.seq||{});}else{state.instrumentIds=[];state.seq={};}$('songNext').disabled=false;renderSongs();};root.appendChild(b);}}
function renderInstruments(){const root=$('instrumentGrid');if(!root)return;root.innerHTML='';for(const i of allInst()){const b=document.createElement('button');b.className='inst-card'+(state.instrumentIds.includes(i.id)?' selected':'');b.innerHTML=`<span class="inst-icon">${i.image?`<img src="${i.image}" alt="">`:i.icon||'♪'}</span><span>${esc(i.name)}</span>`;b.onclick=()=>{const n=state.instrumentIds.indexOf(i.id);n>=0?state.instrumentIds.splice(n,1):state.instrumentIds.push(i.id);renderInstruments();$('instNext').disabled=!state.instrumentIds.length;saveProject();};root.appendChild(b);}$('instNext').disabled=!state.instrumentIds.length;}

function makeDefaultSeq(pattern){let beat=0;return (pattern.items||[]).map(it=>{const e={id:uid('e'),soundId:it.soundId,beat,dur:Number(it.dur||1),pitch:it.pitch||''};beat+=e.dur;return e;});}
function normalizeSeq(a){return (a||[]).map((x,i)=>({id:x.id||uid('e'),soundId:x.soundId,beat:Number.isFinite(x.beat)?x.beat:i,dur:Math.max(.25,Number(x.dur||1)),pitch:x.pitch||''}));}
function currentInstId(){return state.instrumentIds[state.editIndex];}
function pushUndo(){const id=currentInstId();state.undo.push({id,data:structuredClone(state.seq[id]||[])});if(state.undo.length>30)state.undo.shift();}
function renderEditor(){const id=currentInstId(),inst=instById(id);if(!inst)return;$('editTitle').innerHTML=`${inst.image?`<img src="${inst.image}" alt="">`:inst.icon||'♪'} <span>${esc(inst.name)}</span>`;$('editCount').textContent=`${state.editIndex+1} / ${state.instrumentIds.length}`;const presets=$('patternGrid');presets.innerHTML='';if(!state.patterns.length)presets.innerHTML='<div class="empty small">主リズムがまだありません。⚙せんせい →「リズムを作る」で登録できます。</div>';for(const p of state.patterns){const b=document.createElement('button');b.className='pattern-card';b.textContent=p.name;b.onclick=()=>{pushUndo();state.seq[id]=makeDefaultSeq(p);renderTimeline();saveProject();};presets.appendChild(b);}renderTimeline();$('editPrev').disabled=state.editIndex===0;$('editNext').textContent=state.editIndex===state.instrumentIds.length-1?'合奏へ →':'つぎの楽器 →';}
function maxBeat(seq){return Math.max(16,...seq.map(x=>x.beat+x.dur))+4;}
function renderTimeline(){const id=currentInstId();const seq=normalizeSeq(state.seq[id]);state.seq[id]=seq;const root=$('timeline');root.innerHTML='';const total=maxBeat(seq);root.style.width=`${(total+PRE_ROLL)*PX_PER_BEAT}px`;for(let b=0;b<=total;b++){const line=document.createElement('div');line.className='beat-line'+(b%4===0?' bar':'');line.style.left=`${(PRE_ROLL+b)*PX_PER_BEAT}px`;line.innerHTML=b%4===0?`<span>${b}</span>`:'';root.appendChild(line);}for(const e of seq)root.appendChild(eventEl(e));const add=document.createElement('button');add.className='add-event';add.textContent='＋';add.style.left=`${(PRE_ROLL+total-2)*PX_PER_BEAT}px`;add.onclick=()=>openAdd(total-2);root.appendChild(add);}
function eventEl(e){const s=soundById(e.soundId)||{name:'？'};const d=document.createElement('div');d.className='event-card';d.dataset.id=e.id;d.style.left=`${(PRE_ROLL+e.beat)*PX_PER_BEAT}px`;d.style.width=`${Math.max(54,e.dur*PX_PER_BEAT-6)}px`;if(e.pitch&&PITCH_COLORS[e.pitch])d.style.setProperty('--pitch',PITCH_COLORS[e.pitch]);d.innerHTML=`<button class="event-x" aria-label="削除">×</button><b>${esc(s.name)}</b>${e.pitch?`<span class="pitch">${esc(e.pitch)}</span>`:''}<span class="handle">↔</span>`;d.querySelector('.event-x').onclick=ev=>{ev.stopPropagation();pushUndo();state.seq[currentInstId()]=state.seq[currentInstId()].filter(x=>x.id!==e.id);renderTimeline();saveProject();};let mode='move',startX=0,startBeat=e.beat,startDur=e.dur;const down=ev=>{if(ev.target.classList.contains('handle'))mode='resize';else if(ev.target.closest('.event-x'))return;else mode='move';startX=ev.clientX;startBeat=e.beat;startDur=e.dur;pushUndo();d.setPointerCapture?.(ev.pointerId);};const move=ev=>{if(!d.hasPointerCapture?.(ev.pointerId))return;const delta=(ev.clientX-startX)/PX_PER_BEAT;if(mode==='move'){e.beat=snap(startBeat+delta);d.style.left=`${(PRE_ROLL+e.beat)*PX_PER_BEAT}px`;}else{e.dur=Math.max(.25,snap(startDur+delta));d.style.width=`${Math.max(54,e.dur*PX_PER_BEAT-6)}px`;}};const up=ev=>{if(d.hasPointerCapture?.(ev.pointerId))d.releasePointerCapture(ev.pointerId);saveProject();};d.addEventListener('pointerdown',down);d.addEventListener('pointermove',move);d.addEventListener('pointerup',up);d.addEventListener('dblclick',()=>openEventEdit(e));return d;}
function openAdd(beat){$('addSoundGrid').innerHTML='';for(const s of state.sounds){const b=document.createElement('button');b.textContent=s.name;b.onclick=()=>{pushUndo();const id=currentInstId();(state.seq[id]||=[]).push({id:uid('e'),soundId:s.id,beat:snap(beat),dur:Number(s.dur||1),pitch:s.pitch||''});closeModal('addModal');renderTimeline();saveProject();};$('addSoundGrid').appendChild(b);}if(!state.sounds.length)$('addSoundGrid').innerHTML='<div class="empty small">⚙せんせいで音を登録してください。</div>';openModal('addModal');}
function openEventEdit(e){$('eventPitch').value=e.pitch||'';$('eventDur').value=e.dur;$('eventSave').onclick=()=>{pushUndo();e.pitch=$('eventPitch').value;e.dur=Math.max(.25,Number($('eventDur').value)||1);closeModal('eventModal');renderTimeline();saveProject();};openModal('eventModal');}
function undo(){const u=state.undo.pop();if(!u)return toast('もどせる操作がありません');state.seq[u.id]=u.data;renderTimeline();saveProject();}

function renderPerformance(){const s=selectedSong();$('perfMeta').textContent=`${s?.name||''}・${Number(s?.bpm||120).toFixed(1)} BPM`;const root=$('scoreRows');root.innerHTML='';for(const id of state.instrumentIds){const inst=instById(id),seq=normalizeSeq(state.seq[id]);const row=document.createElement('div');row.className='score-row';row.dataset.inst=id;row.innerHTML=`<button class="part-label"><span>${inst?.image?`<img src="${inst.image}" alt="">`:inst?.icon||'♪'}</span><b>${esc(inst?.name||'')}</b></button><div class="track"></div>`;const track=row.querySelector('.track');const total=Math.max(32,...seq.map(x=>x.beat+x.dur));track.style.width=`${(total+PRE_ROLL)*PX_PER_BEAT}px`;for(const e of seq){const snd=soundById(e.soundId)||{name:'？'};const x=document.createElement('div');x.className='perf-event';x.dataset.beat=e.beat;x.style.left=`${(PRE_ROLL+e.beat)*PX_PER_BEAT}px`;x.style.width=`${Math.max(54,e.dur*PX_PER_BEAT-6)}px`;if(e.pitch&&PITCH_COLORS[e.pitch])x.style.setProperty('--pitch',PITCH_COLORS[e.pitch]);x.innerHTML=`<b>${esc(snd.name)}</b>${e.pitch?`<span>${esc(e.pitch)}</span>`:''}`;track.appendChild(x);}row.querySelector('.part-label').onclick=()=>{state.soloId=state.soloId===id?null:id;document.querySelectorAll('.score-row').forEach(r=>r.classList.toggle('hidden-part',state.soloId&&r.dataset.inst!==state.soloId));$('allParts').hidden=!state.soloId;};root.appendChild(row);}applyPosition(0);}
function applyPosition(t){const s=selectedSong();const bpm=Number(s?.bpm||120),beatDur=60/bpm;const shift=Number(s?.offsetBeats||0);const beat=t/beatDur+shift;document.querySelectorAll('.track').forEach(tr=>tr.style.transform=`translate3d(${-beat*PX_PER_BEAT}px,0,0)`);document.querySelectorAll('.perf-event').forEach(e=>{const diff=Math.abs(Number(e.dataset.beat)-beat);e.classList.toggle('hit',diff<.13);});}
async function prepareAudio(){const s=selectedSong();if(!s?.blob)throw new Error('音源がありません');const a=$('audio');if(a._url)URL.revokeObjectURL(a._url);a._url=URL.createObjectURL(s.blob);a.src=a._url;a.load();await new Promise(res=>{if(a.readyState>=1)return res();a.onloadedmetadata=res;setTimeout(res,1500);});}
function tick(){if(!state.playing)return;const a=$('audio');applyPosition(a.currentTime||0);updateTime();if(a.ended){state.playing=false;return;}state.raf=requestAnimationFrame(tick);}
function updateTime(){const a=$('audio');$('time').textContent=`${fmt(a.currentTime)} / ${fmt(a.duration)}`;if(Number.isFinite(a.duration)&&a.duration>0)$('seek').value=(a.currentTime/a.duration)*1000;}
const fmt=n=>!Number.isFinite(n)?'0:00':`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
async function play(){if(!$('audio').src)await prepareAudio();await $('audio').play();state.playing=true;cancelAnimationFrame(state.raf);state.raf=requestAnimationFrame(tick);}
function pause(){state.playing=false;cancelAnimationFrame(state.raf);$('audio').pause();}
function stop(){pause();$('audio').currentTime=0;applyPosition(0);updateTime();}

function openModal(id){$(id).hidden=false;}function closeModal(id){$(id).hidden=true;}
function fileData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file);});}
async function addSong(file){const name=file.name.replace(/\.[^.]+$/,'');const song={id:uid('song'),kind:'song',name,bpm:120,offsetBeats:0,mime:file.type||'audio/mpeg',blob:file,createdAt:Date.now()};await put(song);state.songs.push(song);state.songId=song.id;renderSongs();$('songNext').disabled=false;toast('曲を保存しました');}
async function addInstrument(){const name=$('instName').value.trim();if(!name)return toast('楽器名を入れてください');const f=$('instImage').files?.[0];const i={id:uid('custom'),kind:'instrument',name,icon:'♪',image:f?await fileData(f):null};await put(i);state.instruments.push(i);$('instName').value='';$('instImage').value='';renderTeacherInstruments();renderInstruments();toast('楽器を保存しました');}
async function addSound(){const name=$('soundName').value.trim();if(!name)return toast('音のことばを入れてください');const s={id:uid('sound'),kind:'sound',name,dur:Math.max(.25,Number($('soundDur').value)||1),pitch:$('soundPitch').value};await put(s);state.sounds.push(s);$('soundName').value='';renderTeacherSounds();toast('音を保存しました');}
async function addPattern(){const name=$('patternName').value.trim();const ids=[...$('patternBuilder').querySelectorAll('[data-sound]')].map(x=>x.dataset.sound);if(!name||!ids.length)return toast('名前と音を入れてください');const p={id:uid('pattern'),kind:'pattern',name,items:ids.map(id=>{const s=soundById(id);return{soundId:id,dur:s?.dur||1,pitch:s?.pitch||''};})};await put(p);state.patterns.push(p);$('patternName').value='';$('patternBuilder').innerHTML='';renderPatternPalette();toast('主リズムを保存しました');}
function renderTeacherSounds(){const root=$('soundList');root.innerHTML='';for(const s of state.sounds){const r=document.createElement('div');r.className='teacher-row';r.innerHTML=`<span>${esc(s.name)} ${s.pitch?`(${s.pitch})`:''}</span><button>削除</button>`;r.querySelector('button').onclick=async()=>{await del(s.id);state.sounds=state.sounds.filter(x=>x.id!==s.id);renderTeacherSounds();renderPatternPalette();};root.appendChild(r);}renderPatternPalette();}
function renderPatternPalette(){const root=$('patternPalette');if(!root)return;root.innerHTML='';for(const s of state.sounds){const b=document.createElement('button');b.textContent=s.name;b.onclick=()=>{const x=document.createElement('span');x.dataset.sound=s.id;x.className='builder-chip';x.textContent=s.name;x.onclick=()=>x.remove();$('patternBuilder').appendChild(x);};root.appendChild(b);}}
function renderTeacherInstruments(){const root=$('customInstList');root.innerHTML='';for(const i of state.instruments){const r=document.createElement('div');r.className='teacher-row';r.innerHTML=`<input value="${esc(i.name)}"><button>保存</button><button>削除</button>`;const [save,remove]=r.querySelectorAll('button');save.onclick=async()=>{i.name=r.querySelector('input').value.trim()||i.name;await put(i);renderTeacherInstruments();renderInstruments();};remove.onclick=async()=>{await del(i.id);state.instruments=state.instruments.filter(x=>x.id!==i.id);state.instrumentIds=state.instrumentIds.filter(x=>x!==i.id);renderTeacherInstruments();renderInstruments();};root.appendChild(r);}}
function refreshTeacher(){const s=selectedSong();$('bpmValue').textContent=s?Number(s.bpm||120).toFixed(1):'---';$('offsetValue').textContent=s?Number(s.offsetBeats||0).toFixed(2):'---';renderTeacherSounds();renderTeacherInstruments();}
async function adjustBpm(d){const s=selectedSong();if(!s)return toast('先に曲を選んでください');s.bpm=Math.max(20,Math.min(300,Math.round((Number(s.bpm||120)+d)*10)/10));await put(s);$('bpmValue').textContent=s.bpm.toFixed(1);renderSongs();if(state.screen==='performance')applyPosition($('audio').currentTime||0);}
async function adjustOffset(d){const s=selectedSong();if(!s)return toast('先に曲を選んでください');s.offsetBeats=Math.round((Number(s.offsetBeats||0)+d)*100)/100;await put(s);$('offsetValue').textContent=s.offsetBeats.toFixed(2);if(state.screen==='performance')applyPosition($('audio').currentTime||0);}
async function backup(){const rows=await getAll();const out=[];for(const x of rows){const y={...x};if(x.kind==='song'&&x.blob)y.blobData=await fileData(x.blob),delete y.blob;out.push(y);}const blob=new Blob([JSON.stringify({version:4,rows:out})],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='digital-score-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
async function restore(file){const data=JSON.parse(await file.text());for(const x of data.rows||[]){if(x.kind==='song'&&x.blobData){const r=await fetch(x.blobData);x.blob=await r.blob();delete x.blobData;}await put(x);}await load();toast('バックアップを読み込みました');}

function bind(){
 $('teacherBtn').onclick=()=>{refreshTeacher();openModal('teacherModal');};$('teacherClose').onclick=()=>closeModal('teacherModal');
 $('songNext').onclick=()=>{renderInstruments();show('instrument');};$('instBack').onclick=()=>show('song');$('instNext').onclick=()=>{state.editIndex=0;renderEditor();show('edit');};
 $('editPrev').onclick=()=>{if(state.editIndex>0){state.editIndex--;renderEditor();}};$('editNext').onclick=()=>{if(state.editIndex<state.instrumentIds.length-1){state.editIndex++;renderEditor();}else{renderPerformance();show('performance');}};
 $('undoBtn').onclick=undo;$('clearBtn').onclick=()=>{pushUndo();state.seq[currentInstId()]=[];renderTimeline();saveProject();};
 $('reselectBtn').onclick=()=>{$('patternGrid').scrollIntoView({behavior:'smooth',block:'center'});};$('addAtEnd').onclick=()=>openAdd(maxBeat(state.seq[currentInstId()]||[])-4);
 $('playBtn').onclick=play;$('pauseBtn').onclick=pause;$('stopBtn').onclick=stop;$('editFromPerf').onclick=()=>{pause();state.editIndex=0;renderEditor();show('edit');};$('allParts').onclick=()=>{state.soloId=null;document.querySelectorAll('.score-row').forEach(r=>r.classList.remove('hidden-part'));$('allParts').hidden=true;};
 $('seek').oninput=()=>{const a=$('audio');if(Number.isFinite(a.duration))a.currentTime=Number($('seek').value)/1000*a.duration;applyPosition(a.currentTime||0);updateTime();};
 $('fullscreen').onclick=()=>{const el=document.documentElement;if(!document.fullscreenElement)el.requestFullscreen?.();else document.exitFullscreen?.();};
 $('songFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('audio/')&&!/\.(mp3|m4a|wav|aac)$/i.test(f.name))return toast('MP3・M4A・WAVなどの音声を選んでください');try{await addSong(f);}catch(err){console.error(err);toast('曲を保存できませんでした');}e.target.value='';};
 $('addInstBtn').onclick=addInstrument;$('addSoundBtn').onclick=addSound;$('savePatternBtn').onclick=addPattern;
 document.querySelectorAll('[data-bpm]').forEach(b=>b.onclick=()=>adjustBpm(Number(b.dataset.bpm)));document.querySelectorAll('[data-offset]').forEach(b=>b.onclick=()=>adjustOffset(Number(b.dataset.offset)));
 $('backupBtn').onclick=backup;$('restoreFile').onchange=async e=>{const f=e.target.files?.[0];if(f)try{await restore(f);}catch(err){console.error(err);toast('読み込みに失敗しました');}e.target.value='';};
 $('eventCancel').onclick=()=>closeModal('eventModal');$('addClose').onclick=()=>closeModal('addModal');
 document.querySelectorAll('.modal-backdrop').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.hidden=true;}));
}

document.addEventListener('DOMContentLoaded',async()=>{bind();await load();show('song');if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});});
